# Generated by Django 3.2.8 on 2021-10-15 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abstractapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='full_name',
        ),
    ]
