# Generated by Django 3.2.8 on 2021-10-15 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abstractapp', '0002_rename_first_name_user_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='full_name',
            new_name='name',
        ),
    ]
