# Generated by Django 3.2.8 on 2021-10-17 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstractapp', '0003_rename_full_name_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=250)),
                ('ptitle', models.TextField(max_length=300)),
                ('cat', models.CharField(max_length=20)),
                ('prize', models.BigIntegerField(max_length=5)),
                ('offer', models.IntegerField(max_length=3)),
                ('image', models.ImageField(max_length=500, upload_to='')),
                ('total', models.IntegerField(max_length=5)),
                ('aval', models.IntegerField(max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
