# Generated by Django 3.2.8 on 2021-10-18 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstractapp', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='cuntry',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='landmark',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pin',
            field=models.IntegerField(default=None, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='road',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
