# Generated by Django 3.2.8 on 2021-10-18 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abstractapp', '0006_auto_20211017_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cuntry',
        ),
        migrations.RemoveField(
            model_name='user',
            name='landmark',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='road',
        ),
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
    ]
