# Generated by Django 3.2.8 on 2021-10-18 16:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abstractapp', '0007_auto_20211017_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(max_length=5)),
                ('total', models.FloatField(max_length=10)),
                ('order_data', models.DateField(default=datetime.date(2021, 10, 18))),
                ('order_time', models.TimeField(default=datetime.datetime(2021, 10, 18, 11, 24, 35, 76343))),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abstractapp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
