# Generated by Django 3.2.8 on 2021-10-18 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstractapp', '0008_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rate',
            field=models.IntegerField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 11, 28, 0, 825979)),
        ),
    ]
