# Generated by Django 3.2.8 on 2021-10-18 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstractapp', '0009_auto_20211018_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='rate',
            new_name='prize',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='total',
            new_name='total_prize',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 11, 30, 55, 575412)),
        ),
    ]
