# Generated by Django 3.2.8 on 2021-10-18 20:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstractapp', '0012_auto_20211018_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 18, 15, 18, 9, 296012)),
        ),
        migrations.AlterField(
            model_name='user',
            name='cuntry',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
