# Generated by Django 3.2.8 on 2021-10-25 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstractapp', '0016_auto_20211021_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_data',
            field=models.DateField(default=datetime.date(2021, 10, 25)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 25, 9, 17, 36, 955762)),
        ),
    ]
