# Generated by Django 3.2.8 on 2021-11-03 21:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstractapp', '0018_auto_20211103_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_type',
            field=models.CharField(choices=[('/Pies', '/Pies'), ('/Kg', '/Kg'), ('/Packet', '/Packet')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.TimeField(default=datetime.datetime(2021, 11, 3, 16, 25, 27, 354267)),
        ),
    ]
