# Generated by Django 3.2.8 on 2021-11-04 02:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstractapp', '0019_auto_20211103_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_address',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.TimeField(default=datetime.datetime(2021, 11, 3, 21, 2, 3, 842332)),
        ),
    ]
