# Generated by Django 3.2.8 on 2021-11-04 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstractapp', '0020_auto_20211103_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_data',
            field=models.DateField(default=datetime.date(2021, 11, 4)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.TimeField(default=datetime.datetime(2021, 11, 4, 11, 28, 25, 106734)),
        ),
        migrations.AlterField(
            model_name='product',
            name='prize',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
