# Generated by Django 3.2.8 on 2021-11-04 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstractapp', '0023_auto_20211104_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.TimeField(default=datetime.datetime(2021, 11, 4, 11, 32, 27, 329081)),
        ),
        migrations.AlterField(
            model_name='order',
            name='prize',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
