# Generated by Django 3.2.8 on 2021-11-05 00:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstractapp', '0025_auto_20211104_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.TimeField(default=datetime.datetime(2021, 11, 4, 19, 40, 10, 296737)),
        ),
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Vegitables', 'Vegitables'), ('Womens Clothes', 'Womans Clothes'), ('Mens Clothes', 'Mens Clothes'), ('Toys & Taddy', 'Toys & Taddy')], max_length=20),
        ),
    ]
