# Generated by Django 3.2.8 on 2021-11-14 22:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstractapp', '0027_auto_20211104_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_data',
            field=models.DateField(default=datetime.date(2021, 11, 14)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.TimeField(default=datetime.datetime(2021, 11, 14, 16, 10, 38, 74160)),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity_type',
            field=models.CharField(choices=[('/Piece', '/Piece'), ('/Kg', '/Kg'), ('/Packet', '/Packet')], max_length=20),
        ),
    ]
