# Generated by Django 4.0.1 on 2022-03-04 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstractapp', '0029_alter_order_order_data_alter_order_order_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.TimeField(default=datetime.datetime(2022, 3, 4, 18, 36, 30, 396217)),
        ),
        migrations.AlterField(
            model_name='order',
            name='prize',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_prize',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='aval',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='offer',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='prize',
            field=models.BigIntegerField(),
        ),
    ]
