# Generated by Django 4.0.1 on 2022-03-04 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstractapp', '0030_alter_order_order_time_alter_order_prize_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.TimeField(default=datetime.datetime(2022, 3, 4, 18, 37, 33, 277433)),
        ),
        migrations.AlterField(
            model_name='product',
            name='total',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='pin',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
